# executable files for this directory
OBJECTS = add.o add_item.o add_item2.o avg_price.o \
		  for_ex.o forcount.o item_io.o \
		  main_only.o mysum.o occurs.o whilecount.o

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ../GNU_makefile_template

add_item.o add_item2.o avg_price.o item_io.o: Sales_item.h
